#!/bin/bash

branch_path="stash-file"

if [[ ! $1 ]]; then
  git branch --list $branch_path/*
  exit 0
fi

file="$1"
shift

if [[ ! -f $file ]]; then
  echo "error: file '${file}' doesn't exist."
  exit 1
fi

branch="$branch_path/$file"
if [[ "$(git rev-parse --verify --quiet $branch)" != "" ]]; then
  echo "error: branch with name '${branch}' already exists."
  exit 2
fi

# $path will be empty if $file isn't being tracked
path="$(git ls-files ${file})"
head="$(git rev-parse HEAD)"

if [[ ! "$path" ]]; then
  git add "$file"
else
  git commit -m temp
fi

git commit $@ -- $file
git branch "$branch"
git reset --soft "$head"

if [[ ! "$path" ]]; then
  git reset -q -- "$file"
  rm "$file"
else
  git checkout "$head" -- "$file"
fi

git show "$branch"
